### ISSUE TITLE
WoWLAN not working for 65OLED754

### ISSUE THREAD

**Issue by Thomas-Geraghty** [vniehues/homebridge-saphi-tv#17]
**Describe The Bug:**

Unable to wake up the TV from standby using WoWLAN

**To Reproduce:**

TV can be turned off by power button within Homekit, button will then not turn device back on when clicked again. WoWL packet will be sent correctly but will not wake device.

**Expected behavior:**

The device to awake from standby

**Plugin Config:**

```json
{
    "name": "Living Room TV",
    "ip_adress": "192.168.10.40",
    "wol_adress": "wol://XX:XX:XX:XX:XX",
    "has_tv_channels": false,
    "channel_setup_popup_time": 2250,
    "startup_time": 15,
    "timeout": 5,
    "input_delay": 650,
    "api_version": 6,
    "api_port_no": 1925,
    "protocol": "http",
    "polling_interval": 15,
    "has_ambilight": false,
    "has_ambihue": true,
    "ambi_poweroff": false,
    "ambi_poweron": false,
    "inputs": [
        {
            "name": "hdmi1",
            "type": "SOURCE",
            "position": 1
        }
    ],
    "platform": "SaphiTV"
}
```

I did some digging on this, and it seems like WoWLAN doesn't actually turn on my TV. Sending the 'Standby' key, will put the device into Standby, and sending the same key input again will wake it up. This seems to be the only way I can get the TV returning from sleep. I have WoWLAN enabled within my TV settings.

**Comment by vniehues** [comment]
Hi @Thomas-Geraghty thanks for filing this issue.
I can see you already took a look at #15. Did you also try the troubleshooting I mentioned in there? Especially the Hue Remote App for your Phone and Sending a WOL Request directly from your PI.

You said you did some digging, are you able to send commands to your TV? If yes, please turn off your tv, send a WOL packet and then send the following request to your TV: 

`<IP>/powerstate` 
with this body:
`{ powerstate: 'On' }`

**Comment by Thomas-Geraghty** [comment]
Moved these both onto the same VLAN and updated the TV, seems to work now but not sure why! I will reopen this if the issue returns, thanks for your help!
