### ISSUE TITLE
WOL Issue

### ISSUE THREAD

**Issue by ccarlik** [vniehues/homebridge-saphi-tv#18]
Hi there

I’ve installed this plugin and it’s working great for power off. For power on it will only work if I press the button / send the commend twice. 
I’m using the beta plugin.

let me know if you have any ideas on how to resolve.

**Comment by vniehues** [comment]
Hey sorry for the late reply!

As you've probable already seen from the closed issues, WOL seems to be really tricky. 
Anyways I still wanna try to help you.

Can you just verify that I understood everything correctly?
1. TV is off, you press the "power button" in Homekit and it stays off.
2. You press the "power button" in Homekit again and now the TV turns on.
3. You press the "power button" in Homekit again and the TV turns off.
Correct?

If that is the case I _might_ have an idea for a fix which would be sending the "powerstate: on" command after WOL but that would require an update from my side.

**Comment by ccarlik** [comment]
Thanks for getting back to me.

your summary is exactly correct.

**Comment by vniehues** [comment]
Okay thank you.
As you can see from the commit history, i've not worked with this code in a loooong time but I'll have a look at it.

I will get back to you ASAP :)

**Comment by vniehues** [comment]
@ccarlik I just published a new beta. This is just the quickest implementation of my idea for a fix. Please keep in mind that this is completely untested - but it might just do the trick for you.
Please report back when you tried the newest version.

Edit: you can install the latest beta using the config UI or the following command:
`sudo npm install -g homebridge-saphi-tv@beta`

**Comment by ccarlik** [comment]
@vniehues Unfortunately this hasn't worked, it's been removed as an accessory now

Logs;

20/11/2021, 16:41:40Saphi Tv BridgeConfiguration change
20/11/2021, 16:41:40saphitvbridge stopping
20/11/2021, 16:41:44Saphi Tv Bridge starting
20/11/2021, 16:41:46Saphi Tv BridgeLoaded plugin 'homebridge-saphi-tv'
20/11/2021, 16:41:46Saphi Tv BridgeLoading 1 platforms...
20/11/2021, 16:41:46Saphi Tv BridgePhilips TVFinished initializing platform: SaphiTV
20/11/2021, 16:41:46Saphi Tv BridgePhilips TVFinished launching platform: SaphiTV
20/11/2021, 16:41:46Saphi Tv BridgePhilips TVremoving all accessories
20/11/2021, 16:41:46Saphi Tv BridgeWARNINGunhandled rejection: TypeError: Cannot read property 'filter' of undefined

**Comment by vniehues** [comment]
That is probably a bug another user just reported to me as well. 

If it is in fact the same problem you can just add an input source (one is enough) to work around this bug. 

I will fix it in the next update.

**Comment by ccarlik** [comment]
Ah thanks, that resolved it - however power on isn't working still (now, not even if pressed twice)

**Comment by vniehues** [comment]
Okay at least we're one step closer. 

Please turn off your TV, ssh into your Pi and execute the following commands:

```
sudo apt-get install wakeonlan
wakeonlan YOUR_MAC_ADDRESS
```

This should turn your TV on. 

Please report back if that worked.

**Comment by ccarlik** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package MYMACADDRESS

*removed Mac address for privacy

**Comment by vniehues** [comment]
Did you execute those 2 lines as one command? 
You need to run each line individually.

**Comment by ccarlik** [comment]
haha of course they do lol

executed - no result

**Comment by vniehues** [comment]
Damn... in that case your Pi cannot send WOL packages to your TV. 
This could be due to a number of reasons. 

Please do all the basic troubleshooting like making sure that WOL is turned on on your TV and the TV is in the same subnet / vlan as the Pi. 

Also you can take a look at the following issues (or others):
#17 
#3 

Unfortunately as long as your Pi can not successfully send WOL packages to your TV, I can't really help you. 

If you manage to fix that issue but still experience problems using the plugin, please open an issue again so I can try to help you :)

Good luck!
