### ISSUE TITLE
More than 1 Tv

### ISSUE THREAD

**Issue by FRemo24** [vniehues/homebridge-saphi-tv#19]
**Describe Your Problem:**
Hi, if I try to set 2 TV, I get a warning that says that future HB versions will not supported multiple configuration… is there a solution?

**Comment by vniehues** [comment]
Hi @FRemo24 please excuse the late response - I did not see the notification.

It should work just fine when you install one of the latest homebridge versions.
You can then just use the config ui menu and click on "Add Platform".
