### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by Dippely** [vniehues/homebridge-saphi-tv#22]
Great plugin, works like a charm changing source and turning the TV on/off. 

However, i'm not able to get the volume control to show. I must be missing config for this but i'm not able to figure out what is missing.

**Comment by vniehues** [comment]
Hey @Dippely 

I think this might be a misunderstanding. The volume controls only work within the "tv remote" that you can add to your control center. 
When you pull down the cc and open the remote app, you will be able to adjust the tv volume by using your hardware volume buttons on your iPhone. 

If this is not a misunderstanding and this functionality indeed doesn't work, please report back and I'll take a closer look :)
