### ISSUE TITLE
Allow input of ISDB sub-channel numbers

### ISSUE THREAD

**Issue by javicuna** [vniehues/homebridge-saphi-tv#4]
Hi there!
Just a question: Is there a way to allow the "Dot" character for a channel position? I have a 55PUD6703 (ISDB-Tb, API 6.1), and it only allows me to add main sub-channels (the .1) of TV stations.

Thanks beforehand.

**Comment by vniehues** [comment]
Hi @javicuna :)

I just checked the API-Documentation and I can enable sending a "Dot" to the TV.
I have never heard of sub-channels for tv-channels. Can you explain how this works?
Which country are you in? (if you don't mind telling me)

It would be nice if you could write every key press you do (with the remote) and what the result is.
Example: 
"Watch TV -> 3 -> 4 -> Confirm (ok) results in the TV Channel DMAX being played on my TV."

That way I can figure out where I need to send the "Dot" and when to send it.
I will then release an update with the functionality.

**Comment by javicuna** [comment]
Sure!
I'm in Chile, and the sub channel is part of the standard for ISDB (used in Japan and South America) and ATSC (Used in North America). Basically you can cram several stations in the same frequency. For example, all TV stations here have the main channels in the .1 subchannel, and educational stations in the .2 subchannel.

So, the keypress would be "Watch TV → 1 → 3 → . → 1 → OK" for Canal 13 (13.1) and "Watch TV → 1 → 3 → . → 2 → OK" for TV Educa (13.2)

There's more information on the [Wikipedia article](https://en.wikipedia.org/wiki/Digital_subchannel) for it.

**Comment by vniehues** [comment]
Wow I've never heard of that haha
Thank you for the in-depth explanation! It looks like this might be an easy addition! 
I'm currently working on restructuring the plugin and moving all the switches for inputs to a second accessory (remote) to keep the home app clean. That update will also include the ability to select sub-channels.
I'll update you here once that (big) update is done :)

**Comment by vniehues** [comment]
Hey @javicuna I have a prototype running but my TV doesn't accept the "Dot". That might be because im located in Germany. 
Could you provide a picture of your TV Remote? That could help my with figuring out the needed inputs. 
Also, you can install the prototype with the following command: 

```
sudo npm install homebridge-saphi-tv@beta
```

There is no documentation for that prototype right now. It will expose 2 Accessories: 
- the TV with power & inputs as a selector
- a remote with a switch for ambilight and all inputs as outlets (allows siri to "turn them on")
If you decide to test the current beta, please add both accessories to your home-app. They have the same code as your homebridge.
An input with subchannels should be added just like this: 12.2 
Please report back how this beta version works for you :)

**Comment by javicuna** [comment]
Sure thing, here's a picture of the remote:

![IMG_3486](https://user-images.githubusercontent.com/32501519/107938965-d96acd00-6f64-11eb-81f2-b41c53c7f595.jpeg)

Can't test the beta for a few hours, though. Will report about it later.

**Comment by vniehues** [comment]
Thank you :)
Your remote looks completely different compared to mine! 
Mine doesn't have a dot so chances are good that my tv just wont accept the Dot-Command but yours will.
Please report back if the beta works for you and your issue is resolved

**Comment by javicuna** [comment]
Just tested it and got it working fine, although the web UI converts the dot to a comma (but that's purely cosmetic)
![Captura de Pantalla 2021-02-15 a la(s) 19 18 18](https://user-images.githubusercontent.com/32501519/107998007-ed451c00-6fc2-11eb-8f61-effbd856a913.png)

Thanks!

**Comment by vniehues** [comment]
Im glad it works for you! 
I'll try to fix that cosmetic bug soon but I'll mark this beta as a release candidate. 
Did everything else work for you aswell? - Do you use the external remote accessory?

**Comment by javicuna** [comment]
I couldn't make the TV controls show up, but that's probably something related to my clumsiness.
![IMG_3493](https://user-images.githubusercontent.com/32501519/108077589-730caa00-704b-11eb-81a2-ed0dd4a10f7b.PNG)

**Comment by vniehues** [comment]
The TV-Remote should be available just like the TV. 
In the home app please click on "+" -> add new device -> no code. It should show up there and you should be able to add it with the same code as you added your homebridge and the TV. 
If it doesnt show up I'd like to see your config because it that would be a bug I'd like to fix haha

**Comment by javicuna** [comment]
Only the main device shows up in my HomeKit setup. The volume controls don't show up. 

This is the config for the device:
[config_saphi.txt](https://github.com/vniehues/saphi_tv/files/5992278/config_saphi.txt)

**Comment by vniehues** [comment]
thanks for the config! 

- I released a new beta (which you can install with the same command) which should correctly publish the second accessory.
- Volume controls are currently limited to the control-center remote app. When you open the control-center remote app you can press your iPhone hardware volume buttons to increase / decrease the volume. 
    - In the future I add a slider for it but for now thats all we got..

please report back if this beta works better for you 👍

**Comment by vniehues** [comment]
@javicuna I'm interested in your feedback! Does everything work for you now? :)

**Comment by javicuna** [comment]
Sorry, was out of town. Everything is working fine now, thanks. Guess this issue should be closed.
