### ISSUE TITLE
Setup multiple TV

### ISSUE THREAD

**Issue by tomsteenbakkers** [vniehues/homebridge-saphi-tv#7]
I have installed this plugin and works like a charm. I also used the new HomeBridge function to setup the plugin als a Child Bridge.

Now I want to add a second TV. How can I do that (and is this possible)?

**Comment by vniehues** [comment]
Hey @tomsteenbakkers I'm glad my plugin works for you. 

The plugin itself doesn't support multiple TVs but your Homebridge can have multiple versions of my plugin. 
Setting up the plugin as a child bridge is the right way. 
![image](https://user-images.githubusercontent.com/28765921/108689767-c7a39f80-74f9-11eb-96de-12d6ff657b22.png)
![image](https://user-images.githubusercontent.com/28765921/108689825-dbe79c80-74f9-11eb-9da7-ec1c7a6f4acb.png)
When you click on the wrench here and select JSON Config, You can then click on "Add Platform" to add another installation of the plugin. 
Do this as often as you need to and configure them (need to do it in JSON, config ui is not supported for multiple).
When they're all configured, open the "child-bridges" dialog once again and select a child bridge for each tv - to prevent hangups and errors. 

Please report back if all your TVs work :)

ps: I'm thinking about better multi-tv support but that'll take some time...

**Comment by vniehues** [comment]
@tomsteenbakkers did this workaround work for you?

**Comment by tomsteenbakkers** [comment]
yes it did. Works like a charm

**Comment by vniehues** [comment]
Nice! Thanks for the feedback :)
