### ISSUE TITLE
Can’t add to home 

### ISSUE THREAD

**Issue by ghost** [vniehues/homebridge-saphi-tv#8]
**Describe Your Problem:**
Homebridge is added as a bridge but can find the TV when added device to Home app

![37DAD048-4B80-49A1-A7D7-BF79B8734AF6](https://user-images.githubusercontent.com/73031854/109426853-963e3e80-79e7-11eb-8f0b-ed956fafe72b.jpeg)

Just sticks on this page. 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

{
            "name": "TV",
            "ip_adress": "000.000.00.0 (does say IP) ",
            "wol_adress": "wol://00:00:00:00:00:00 (does say Mac)",
            "has_tv_channels": true,
            "channel_setup_popup_time": 2250,
            "startup_time": 15,
            "timeout": 4,
            "input_delay": 498,
            "api_version": 6,
            "api_port_no": 1925,
            "protocol": "http",
            "polling_interval": 40,
            "has_ambilight": false,
            "has_ambihue": true,
            "ambi_poweroff": true,
            "ambi_poweron": false,
            "inputs": [
                {
                    "name": "Apple TV",
                    "type": "SOURCE",
                    "position": -2
                },
                {
                    "name": "Xbox",
                    "type": "SOURCE",
                    "position": -1
                },
                {
                    "name": "PC",
                    "type": "SOURCE",
                    "position": 0
                }
            ],
            "_bridge": {
                "username": "0E:BB:C4:42:E3:BC",
                "port": 45401
            },
            "platform": "SaphiTV"
        }
    ]

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 0.27
* **Node.js Version**: <14.15.5>
* **NPM Version**: <6.14.11>
* **Operating System**:

**Comment by vniehues** [comment]
Hey @ashleymoat,
Thanks for reaching out! 

Did you try restarting your Homebridge? 
After the restart there should be two sets of entries like these in the logs:
![image](https://user-images.githubusercontent.com/28765921/109430691-f393b900-7a02-11eb-8cba-159377d2da82.png)

You should then be able to add them like you tried.

If they're not present, the plugin fails to initialize the accessories. I would need to check that. 
If these lines however are present in your logs, your local network might be at fault. Can you add other external accessories?

Your config looks good to me. Which version of homebridge are you using? (you entered the plugin version there)

**Comment by ghost** [comment]
![DA2A3C3A-B236-48E7-8E22-D9BD3B678611](https://user-images.githubusercontent.com/73031854/109430973-e2937980-79fb-11eb-9404-b4734cf11f3f.jpeg)

Sorry version 1.3.1
Yes other products seem to add ok. Your beta version does, just not the live version.

thanks

**Comment by vniehues** [comment]
Oh damn... 
Just to clarify, you have the current beta version running without issues but the live version did not work? 

I'll try to release the current beta sometime next week but I want to test it further before doing so.

**Comment by ghost** [comment]
![DBEA42DF-9F01-4D04-8B58-CA4B9DABD718](https://user-images.githubusercontent.com/73031854/109432398-d828ae00-7a02-11eb-8ef6-ea5d53a63c66.jpeg)

I get this error when running the beta. But nothing showing in home app today. Thought I saw a remote to add yesterday though

**Comment by vniehues** [comment]
Strange. I will look into this error today but I get that Error (it's only a warning) as well and it's running and connecting perfectly on my network. 
I'll do some digging and update you later

**Comment by vniehues** [comment]
I was able to reproduce your error on the current version and I also fixed it. 
I needed to change my Homebrige network settings to use 'Ciao' as mDNS advertiser and I specified the network interface it should use. That fixed it in my case. 
I also observed that the TV did show up for < 5 seconds before disappearing. This makes me believe that I had your exact error.
![image](https://user-images.githubusercontent.com/28765921/109566734-96703400-7ae4-11eb-81ca-65fb879e24f9.png)

Please report back how this went for you! 

Version tested: latest beta

**Comment by ghost** [comment]
That worked perfectly. Thank you for your help. Much appreciated

**Comment by vniehues** [comment]
Thanks for the feedback!
I'm glad it's working for you :)
